[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
powdr = { git = "https://github.com/powdr-labs/powdr", branch = "main" }
revm = { git = "https://github.com/powdr-labs/revm", branch = "serde-no-std", default-features = false, features = [ "serde" ] }

models = { path = "../models" }
hex = "0.4.3"
env_logger = "0.10.2"
thiserror = "1.0"
serde_json = "1.0.108"
walkdir = "2.4.0"
